spring:
  application:
    name: customer-service
  mongodb:
    database: customerdb
    host: localhost
    port: 27017

server:
  port: 8082

eureka:
  client:
    enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
